server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
data:
  database:
    driver: mysql
    source: root:dangerous@tcp(127.0.0.1:3306)/pallas?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password:
    db: 0
    cache_expiration: 1800s
    read_timeout: 0.2s
    write_timeout: 0.2s
  cache:
    lfu_size: 1000
    ttl: 60s
secret:
  session:
    session_key: "hello"