version: '3.4'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=dangerous"
    ports:
      - "3306:3306"
    networks:
      net:
        aliases:
          - mysql

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dangerous
      POSTGRES_DB: pallas
    ports:
      - "5432:5432"
    networks:
      net:
        aliases:
          - postgres

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      #      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
      - ./redis/logs:/logs
    ports:
      - "6379:6379"
    networks:
      net:
        aliases:
          - redis

networks:
  net:
    driver: bridge