name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
      options: --user root
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: dangerous
          MYSQL_DATABASE: pallas
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: dangerous
          POSTGRES_DB: pallas
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache bash build-base findutils git protobuf protobuf-dev tar

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trust repository
        run: |
          git config --global --add safe.directory "*"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.work.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate
        run: |
          make init
          make api
          make conf
          make generate
          make wire

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test